[install.filesystem.root]
type = "xfs"

# We add the ignition.firstboot and ignition.platform.id for testing purpose
# as b-i-b does not support yet adding ignition osbuild stage to the generated manifest
# remove those kargs once supported.
[install]
kargs = ["rw", "console=tty0", "console=ttyS0", "$ignition_firstboot", "ignition.platform.id=qemu"]
# We dont't want bootc to append the kargs list with boot=UUID= and root=UUID= info
# as CoreOS already handles this.
root-mount-spec = ""
boot-mount-spec = ""
stateroot = "fedora-coreos"

# The bootc binary including the new ostree option haven't landed yet in FCOS
# but we have it in our cosa builder image that we copy/pasted to the target image (see the Containerfile)
[install.ostree]
bls-append-except-default = 'grub_users=""'

[install.bootupd]
skip-boot-uuid = true
