# Image Builder configuration
# MintMaker will bump the digests in this file automatically.
image-builder-cli: "quay.io/jcapitao/image-builder:latest"
builder-image: "quay.io/jcapitao/fedora-bootc-rawhide-standard:unlabeled-fix"
