# Image Builder configuration
# MintMaker will bump the digests in this file automatically.
image-builder-cli: "quay.io/jbtrystramtestimages/ib-cli"
builder-image: "quay.io/bootc-devel/fedora-bootc-rawhide-standard"
