name = "Fedora CoreOS"

# Create an empty Ignition firstboot marker so the Ignition first-boot
# sequence runs on the produced image.
[customizations.ignition.firstboot]
empty = true

# Here live all the kernel arguments that are shared by all
# artifacts on all plateforms.
# Source1: https://github.com/coreos/coreos-assembler/blob/af5d9c39d18741c560802ef5e2ccd23bc631e184/src/osbuild-manifests/build.common.ipp.yaml#L139-L144
# Source2: https://github.com/coreos/fedora-coreos-config/blob/a9547d8c7b90decdd914c20becf56e5614e092bb/image-base.yaml#L10-L12
[customizations.kernel]
append = "mitigations=auto,nosmt"

