name = "Fedora CoreOS"

[customizations]

[customizations.ignition]

[customizations.ignition.firstboot]
empty = true

[customizations.kernel]
append = "mitigations=auto,nosmt ignition.platform.id=qemu"
