# Platform: azure — aarch64
# Canonical source: https://github.com/coreos/fedora-coreos-config/blob/testing-devel/platforms.yaml
[customizations.kernel]
append = "ignition.platform.id=azure console=tty0 console=ttyAMA0,115200n8"
