# Platform: hetzner — aarch64
# Canonical source: https://github.com/coreos/fedora-coreos-config/blob/testing-devel/platforms.yaml
[customizations.kernel]
append = "ignition.platform.id=hetzner console=tty0 console=ttyS0,115200n8"

[customizations.bootloader.grub2]
terminal_input = ["serial", "console"]
terminal_output = ["serial", "console"]
serial = "serial --speed=115200"
