[install.filesystem.root]
type = "xfs"

[install]
# TODO remove when https://github.com/coreos/fedora-coreos-config/pull/4170 merges.
# We don't want bootc to append boot=UUID= and root=UUID= to the kargs list
# as CoreOS already handles this itself.
root-mount-spec = ""
boot-mount-spec = ""
stateroot = "fedora-coreos"

[install.bootupd]
skip-boot-uuid = true
