apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/joelcapitao/bib-fcos-experimentation?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/task: "[.tekton/tasks/image-builder.yaml, .tekton/tasks/build-disk-image-index.yaml]"
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fedora-coreos-rawhide
    appstudio.openshift.io/component: disk-images-rawhide
    pipelines.appstudio.openshift.io/type: build
  name: disk-images-rawhide-pull-request
  namespace: coreos-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/konflux-fedora/coreos-tenant/disk-images-rawhide:on-pr-{{revision}}
  - name: image-expires-after
    value: 5d
  - name: artifacts
    value:
      - qemu
      - metal
  - name: output-name
    value: fedora-coreos-rawhide
  - name: source-image
    value: quay.io/konflux-fedora/coreos-tenant/fedora-coreos-rawhide@sha256:28c7c21910fe0e8f46cb4de2fd866cee7de5b5ef7c9a2215e559bf0f9d981d46
  pipelineSpec:
    description: |
      This pipeline builds Fedora CoreOS disk images (qemu, metal, etc.) for
      multiple artifacts within a single architecture, then assembles them
      into an OCI index.

      The OCI index uses custom platform metadata (platform.os=<artifact>)
      to identify each disk image type, allowing retrieval with:
        oras pull --platform qemu/amd64 <registry>/<repo>:<tag>
    params:
    - description: Source Repository URL
      name: git-url
      type: string
    - default: ""
      description: Revision of the Source Repository
      name: revision
      type: string
    - description: Fully Qualified Output Image
      name: output-image
      type: string
    - default: ""
      description: Image tag expiration time, time values could be something like
        1h, 2d, 3w for hours, days, and weeks, respectively.
      name: image-expires-after
      type: string
    - default: "false"
      description: Enable cache proxy configuration
      name: enable-cache-proxy
    - description: List of artifact types to build (e.g. ["qemu", "metal"]).
      name: artifacts
      type: array
      default:
        - qemu
        - metal
    - description: Base name for the produced disk image file (--output-name).
      name: output-name
      type: string
    - description: Fully qualified pullspec of the upstream FCOS bootc container image.
      name: source-image
      type: string
    tasks:
    - name: init
      params:
      - name: enable-cache-proxy
        value: $(params.enable-cache-proxy)
      taskRef:
        params:
        - name: name
          value: init
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-init:0.4@sha256:5a423246792ac501ea279229b42ee57da9927da441c04b5c9ff86817b0856b08
        - name: kind
          value: task
        resolver: bundles
    - name: clone-repository
      params:
      - name: url
        value: $(params.git-url)
      - name: revision
        value: $(params.revision)
      - name: ociStorage
        value: $(params.output-image).git
      - name: ociArtifactExpiresAfter
        value: $(params.image-expires-after)
      runAfter:
      - init
      taskRef:
        params:
        - name: name
          value: git-clone-oci-ta
        - name: bundle
          value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:13d49df7dc9ae301627e45f95a236011422996152f1bea46cd60217b0f057407
        - name: kind
          value: task
        resolver: bundles
      workspaces:
      - name: basic-auth
        workspace: git-auth
    - name: build-disk-images
      runAfter:
      - clone-repository
      taskRef:
        name: image-builder
      params:
      - name: PLATFORM
        value: linux/amd64
      - name: ARTIFACTS
        value:
          - $(params.artifacts[*])
      - name: SOURCE_IMAGE
        value: $(params.source-image)
      - name: OUTPUT_IMAGE
        value: $(params.output-image)-linux-amd64
      - name: OUTPUT_NAME
        value: $(params.output-name)
      - name: SOURCE_ARTIFACT
        value: $(tasks.clone-repository.results.SOURCE_ARTIFACT)
    - name: build-disk-image-index
      runAfter:
      - build-disk-images
      taskRef:
        name: build-disk-image-index
      params:
      - name: IMAGE
        value: $(params.output-image)
      - name: IMAGES
        value:
          - $(tasks.build-disk-images.results.ARTIFACT_TAGS)
    results:
    - name: IMAGE_URL
      value: $(tasks.build-disk-image-index.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      value: $(tasks.build-disk-image-index.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      value: $(tasks.clone-repository.results.commit)
    workspaces:
    - name: git-auth
      optional: true
  taskRunTemplate:
    serviceAccountName: build-pipeline-disk-images-rawhide
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
